config/routes.rb
Rails.application.routes.draw do
  resources :activity_logs, only: %i[index]

  namespace :api do
    resources :activities, only: %i[index]
    resources :babies, only: %i[index] do
      resources :activity_logs, only: %i[index]
    end
    resources :activity_logs, only: %i[create update]
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :baby
  belongs_to :assistant
  belongs_to :activity

  validate :start_must_be_before_end_time

  scope :finished, ->{where("stop_time IS NOT NULL")}
  scope :in_progress, ->{where("stop_time IS NULL")}

  before_update :set_duration

  def status
    stop_time.nil? ? "En Progreso" : "Terminada"
  end

  private

  def set_duration
    self.duration = (stop_time - start_time).minutes.to_i unless stop_time.nil?
  end

  private

  def start_must_be_before_end_time
    errors.add(:start_time, "must be before stop time") if !stop_time.nil? && start_time > stop_time
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
class Assistant < ApplicationRecord
  has_many :activity_logs
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :activity_logs

  def age_in_months
    (Date.current.year * 12 + Date.current.month) - (birthday.year * 12 + birthday.month)
  end

end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ActionController::Base
  def index
    query = Hash.new
    query[:baby_id] = params[:baby_id] unless params[:baby_id].blank?
    query[:assistant_id] = params[:assistant_id] unless params[:assistant_id].blank?

    query.empty? ? @activity_logs = ActivityLog.all : @activity_logs = ActivityLog.where(query)
    @activity_logs = @activity_logs.finished if params[:status] == "Terminada"
    @activity_logs = @activity_logs.in_progress if params[:status] == "En Progreso"

  end
end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < ApplicationController
  def index
    @activities = Activity.select(:id,:name,:description)
    json_response(@activities)
  end
end

app/controllers/api/activity_logs_controller.rb
class Api::ActivityLogsController < ApplicationController
  def index
    id = params[:baby_id]
    if id.nil?
      @logs = ActivityLog.all
    else
      baby = Baby.find(id)
      @logs = baby.activity_logs.select(:id, :baby_id).as_json
      baby.activity_logs.each_with_index do |al,idx|
        @logs[idx]["assistant"] = al.assistant.name
        @logs[idx]["start_time"] = al.start_time.iso8601
        @logs[idx]["stop_time"] = al.stop_time.iso8601 if al.status == "Terminada"
      end
    end
    json_response(@logs)
  end

  def create
    @activity_log = ActivityLog.create!(activity_log_params)
    json_response(@activity_log, :created)
  end

  def update
    @activity_log = ActivityLog.find(params[:id])
    @activity_log.update!(activity_log_params)
    head :no_content
  end

  def activity_log_params
    params.permit(:activity_id, :baby_id, :assistant_id, :start_time, :stop_time, :comments)
  end
end

app/controllers/api/babies_controller.rb
class Api::BabiesController < ApplicationController
  def index
    @babies = Baby.select(:id,:name,:mother_name,:father_name, :address, :phone).as_json
    Baby.all.each_with_index do |b,idx|
      @babies[idx]["age_in_months"] = b.age_in_months
    end
    json_response(@babies)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include Response
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({message: e.message}, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end

end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/views/activity_logs/_table_row.html.erb
<tr>
  <td><%= log.baby.name %></td>
  <td><%= log.assistant.name %></td>
  <td><%= log.activity.name %></td>
  <td><%= log.start_time.in_time_zone("Mexico City").strftime('%Y-%m-%d %H:%M') %></td>
  <td><%= log.status %></td>
  <td><%= log.duration.nil? || log.duration <= 1 ? "*" : "#{log.duration.to_i} min" %></td>
</tr>

app/views/activity_logs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinedu</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col text-center">
          <h1 class="top-title bold">Log de Actividades</h1>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-8">
          <%= form_tag activity_logs_path(:baby_id, :assistant_id), method: :get, class: "form-inline justify-content-around mb-3" do %>
              <%= select_tag(:baby_id, options_for_select(ActivityLog.joins(:baby).distinct.pluck(:name, :baby_id).sort), prompt: "Seleccionar Bebé", class: "custom-select") %>
              <%= select_tag(:assistant_id, options_for_select(ActivityLog.joins(:assistant).distinct.pluck(:name, :assistant_id).sort), prompt: "Seleccionar Asistente", class: "custom-select") %>
              <%= select_tag(:status, options_for_select([["En Progreso","En Progreso"],["Terminada", "Terminada"]]), prompt: "Seleccionar Estatus", class: "custom-select") %>
              <%= submit_tag("Filtrar", class: "btn btn-primary") %>
          <% end %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-8">
          <table class="table table-sm table-hover table-bordered table-dark" id="logs">
            <thead>
            <tr>
              <th scope="col">Bebé</th>
              <th scope="col">Asistente</th>
              <th scope="col">Actividad</th>
              <th scope="col">Inicio</th>
              <th scope="col">Estatus</th>
              <th scope="col">Duración</th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: "table_row", collection: @activity_logs.order(start_time: :desc), as: :log %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>